export const DISCORD_TOKEN = process.env.DISCORD_TOKEN;
export const APPLICATION_ID = process.env.APPLICATION_ID;
export const GUILD_ID = process.env.GUILD_ID;
export const MOVIE_NIGHT_ROLE = process.env.MOVIE_NIGHT_ROLE;
export const MOVIE_NIGHT_TEXT_CHANNEL = process.env.MOVIE_NIGHT_TEXT_CHANNEL;
export const MOVIE_NIGHT_VOICE_CHANNEL = process.env.MOVIE_NIGHT_VOICE_CHANNEL;
export const OMDB_API_KEY = process.env.OMDB_API_KEY;
export const TMDB_API_KEY = process.env.TMDB_API_KEY;
export const QUEUE_PAGE_COUNT: number = Number(process.env.QUEUE_PAGE_COUNT);
